[package]
name = "constellation-cxx"
version = "0.1.0"
edition = "2021"

[dependencies]
star-constellation = { git = "https://github.com/brave/constellation", rev = "3b34d761341518e97692de3419380600ede1057f" }
cxx = { path = "../../../third_party/rust/cxx/v1/crate" }
# Use following cxx dep if compiling example via Makefile
# cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
name = "constellation_cxx"
crate-type = ["rlib"]
# Use following crate type setting if compiling example via Makefile
# crate-type = ["staticlib"]

# Also, if compiling example, rename build.example.rs to build.rs
